### ISSUE TITLE
repeated CSS

### ISSUE THREAD

**Issue by mattlub** [FACK1/Sporto-.-#15]
You have repeated some CSS inside the media-query:

One example is [here](https://github.com/FACK1/Sporto-.-/blob/4883ae0682b84077ccff1464d679c15b7db75647/css/style.css#L170-L175) and [here](https://github.com/FACK1/Sporto-.-/blob/4883ae0682b84077ccff1464d679c15b7db75647/css/style.css#L275-L283):

Because the CSS cascades, so any rules in the media query are **added** to those outside of the media query.

```css
.my-class {
  width: 50%;
  border: 2px solid red;
}

@media only screen and (min-width: 650px) {

  .my-class {
    width: 100%;
    // the border rule does not need to be added here!
  }

}

```
